name: GHCR Package Deployment

on:
  workflow_run:
    workflows:
      - Release
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read      # Allows reading the repository contents
      packages: write     # Allows publishing to GHCR
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ github.repository }}
          IMAGE_TAG=$(jq -r .version < package.json)

          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag $IMAGE_NAME:$IMAGE_TAG \
            --tag $IMAGE_NAME:latest \
            --push .
